version: "3"

services:
  pokedex:
    container_name: pokedex
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    stdin_open: true
